============================= test session starts =============================
platform win32 -- Python 3.13.1, pytest-8.2.1, pluggy-1.5.0
rootdir: C:\Users\njcro\m7project\backend
configfile: pytest.ini
plugins: Flask-Dance-6.0.0, flask-1.3.0
collected 41 items / 1 error

=================================== ERRORS ====================================
__________________ ERROR collecting tests/test_newsletter.py __________________
venv\Lib\site-packages\_pytest\python.py:492: in importtestmodule
    mod = import_path(
venv\Lib\site-packages\_pytest\pathlib.py:591: in import_path
    importlib.import_module(module_name)
C:\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
venv\Lib\site-packages\_pytest\assertion\rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests\test_newsletter.py:1: in <module>
    from app.routes.newsletter_routes import newsletter_bp
app\routes\__init__.py:14: in <module>
    from app.routes.inventory_routes import inventory_bp
E     File "C:\Users\njcro\m7project\backend\app\routes\inventory_routes.py", line 148
E       r.setex(
E              ^
E   SyntaxError: '(' was never closed
=========================== short test summary info ===========================
ERROR tests/test_newsletter.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 1.61s ===============================
